import { Dish, Order } from './types'

// 模拟菜品数据 - 使用 Unsplash 高质量美食图片
export const mockDishes: Dish[] = [
  {
    id: '1',
    name: '宫保鸡丁',
    description: '经典川菜，鸡肉鲜嫩，花生酥脆',
    price: 38,
    category: '热菜',
    image: 'https://images.unsplash.com/photo-1603360946369-dc9bb6258143?w=800&h=600&fit=crop',
    available: true,
    preparationTime: 15,
    options: [
      {
        id: 'size',
        type: 'radio',
        label: '份量',
        required: true,
        choices: [
          { id: 'small', name: '小份', priceAdjustment: -8, default: false },
          { id: 'medium', name: '中份', priceAdjustment: 0, default: true },
          { id: 'large', name: '大份', priceAdjustment: 10, default: false },
        ],
      },
      {
        id: 'spicy',
        type: 'radio',
        label: '辣度',
        required: true,
        choices: [
          { id: 'none', name: '不辣', priceAdjustment: 0, default: false },
          { id: 'mild', name: '微辣', priceAdjustment: 0, default: true },
          { id: 'medium', name: '中辣', priceAdjustment: 0, default: false },
          { id: 'hot', name: '特辣', priceAdjustment: 0, default: false },
        ],
      },
    ],
  },
  {
    id: '2',
    name: '麻婆豆腐',
    description: '麻辣鲜香，豆腐嫩滑',
    price: 28,
    category: '热菜',
    image: 'https://images.unsplash.com/photo-1585032226651-759b368d7246?w=800&h=600&fit=crop',
    available: true,
    preparationTime: 10,
    options: [
      {
        id: 'spicy',
        type: 'radio',
        label: '辣度',
        required: true,
        choices: [
          { id: 'none', name: '不辣', priceAdjustment: 0, default: false },
          { id: 'mild', name: '微辣', priceAdjustment: 0, default: false },
          { id: 'medium', name: '中辣', priceAdjustment: 0, default: true },
          { id: 'hot', name: '特辣', priceAdjustment: 0, default: false },
        ],
      },
    ],
  },
  {
    id: '3',
    name: '糖醋排骨',
    description: '酸甜可口，外酥里嫩',
    price: 48,
    category: '热菜',
    image: 'https://images.unsplash.com/photo-1529692236671-f1f6cf9683ba?w=800&h=600&fit=crop',
    available: true,
    preparationTime: 20,
  },
  {
    id: '4',
    name: '凉拌黄瓜',
    description: '清爽解腻，夏日佳品',
    price: 18,
    category: '凉菜',
    image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&h=600&fit=crop',
    available: true,
    preparationTime: 5,
  },
  {
    id: '5',
    name: '皮蛋豆腐',
    description: '口感滑嫩，味道鲜美',
    price: 22,
    category: '凉菜',
    image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=800&h=600&fit=crop',
    available: true,
    preparationTime: 5,
  },
  {
    id: '6',
    name: '扬州炒饭',
    description: '粒粒分明，配料丰富',
    price: 25,
    category: '主食',
    image: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=800&h=600&fit=crop',
    available: true,
    preparationTime: 12,
    options: [
      {
        id: 'size',
        type: 'radio',
        label: '份量',
        required: true,
        choices: [
          { id: 'small', name: '小份', priceAdjustment: -5, default: false },
          { id: 'medium', name: '中份', priceAdjustment: 0, default: true },
          { id: 'large', name: '大份', priceAdjustment: 8, default: false },
        ],
      },
      {
        id: 'spicy',
        type: 'radio',
        label: '辣度',
        required: false,
        choices: [
          { id: 'none', name: '不辣', priceAdjustment: 0, default: true },
          { id: 'mild', name: '微辣', priceAdjustment: 0, default: false },
          { id: 'medium', name: '中辣', priceAdjustment: 0, default: false },
        ],
      },
      {
        id: 'addons',
        type: 'checkbox',
        label: '加料',
        required: false,
        choices: [
          { id: 'egg', name: '加鸡蛋', priceAdjustment: 2, default: false },
          { id: 'ham', name: '加火腿', priceAdjustment: 3, default: false },
          { id: 'shrimp', name: '加虾仁', priceAdjustment: 8, default: false },
          { id: 'veg', name: '加时蔬', priceAdjustment: 1, default: false },
        ],
      },
    ],
  },
  {
    id: '7',
    name: '蛋炒饭',
    description: '简单美味，经典主食',
    price: 18,
    category: '主食',
    image: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?w=800&h=600&fit=crop',
    available: true,
    preparationTime: 8,
    options: [
      {
        id: 'size',
        type: 'radio',
        label: '份量',
        required: true,
        choices: [
          { id: 'small', name: '小份', priceAdjustment: -3, default: false },
          { id: 'medium', name: '中份', priceAdjustment: 0, default: true },
          { id: 'large', name: '大份', priceAdjustment: 5, default: false },
        ],
      },
      {
        id: 'addons',
        type: 'checkbox',
        label: '加料',
        required: false,
        choices: [
          { id: 'egg', name: '加鸡蛋', priceAdjustment: 2, default: false },
          { id: 'ham', name: '加火腿', priceAdjustment: 3, default: false },
          { id: 'veg', name: '加青菜', priceAdjustment: 1, default: false },
        ],
      },
    ],
  },
  {
    id: '8',
    name: '西红柿鸡蛋汤',
    description: '酸甜开胃，营养丰富',
    price: 15,
    category: '汤类',
    image: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=800&h=600&fit=crop',
    available: true,
    preparationTime: 10,
  },
  {
    id: '9',
    name: '可乐',
    description: '冰镇可乐，清凉解渴',
    price: 8,
    category: '饮料',
    image: 'https://images.unsplash.com/photo-1554866585-cd94860890b7?w=800&h=600&fit=crop',
    available: true,
    preparationTime: 1,
  },
  {
    id: '10',
    name: '芒果布丁',
    description: '香甜软糯，入口即化',
    price: 18,
    category: '甜点',
    image: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=800&h=600&fit=crop',
    available: true,
    preparationTime: 0,
  },
]

// 模拟订单数据
export const mockOrders: Order[] = [
  {
    id: 'ORD001',
    items: [
      { dish: mockDishes[0], quantity: 1 },
      { dish: mockDishes[5], quantity: 2 },
    ],
    total: 88,
    status: 'preparing',
    customerName: '张三',
    tableNumber: 'A01',
    createdAt: new Date('2024-11-17T10:30:00'),
    updatedAt: new Date('2024-11-17T10:35:00'),
  },
  {
    id: 'ORD002',
    items: [
      { dish: mockDishes[1], quantity: 1 },
      { dish: mockDishes[3], quantity: 1 },
    ],
    total: 46,
    status: 'ready',
    customerName: '李四',
    tableNumber: 'B02',
    createdAt: new Date('2024-11-17T11:00:00'),
    updatedAt: new Date('2024-11-17T11:20:00'),
  },
  {
    id: 'ORD003',
    items: [
      { dish: mockDishes[2], quantity: 1 },
      { dish: mockDishes[7], quantity: 1 },
      { dish: mockDishes[8], quantity: 2 },
    ],
    total: 79,
    status: 'delivered',
    customerName: '王五',
    tableNumber: 'C03',
    createdAt: new Date('2024-11-17T09:45:00'),
    updatedAt: new Date('2024-11-17T10:15:00'),
  },
]
